const texts = {
    laboratory: {
        title: 'El laboratorio',
    },
    developments: {
        title: 'Desarrollos',
    },
    resources: {
        title: 'Repositorio',
        threeDModels: { title: 'Elementos 3D' },
        projects: { title: 'Proyectos' },
        tutorials: { title: 'Tutoriales' },
    },
    services: {
        title: 'Servicios',
    },
    contact: {
        title: 'Contacto',
    },
    login: {
        title: 'Accede a tu cuenta',
        description: 'Utiliza tu correo y contraseña que registraste para acceder a tu cuenta.',
        forgotPassword: '¿Olvidaste tu contraseña?',
        rememberMe: 'Recordar mi contraseña',
        button: 'Iniciar sesión',
        noAccount: '¿No tienes una cuenta?',
    },
    register: {
        title: 'Regístrate',
        description: 'Los datos que proporciones serán usados exclusivamente para fines de autenticación.',
        info: 'Para más información, consulta nuestros',
        placeHolderAccountNumber: 'máximo 8 caracteres',
        placeHolderConfirmPassword: 'contraseña',
        placeHolderPaternalSurname: 'Apellido Paterno',
        placeHolderMaternalSurname: 'Apellido Materno',
        placeHolderName: 'Nombre(s)',
        placeHolderOrigin: 'Institución educativa, organización, etc.',
        placeHolderMajor: 'Selecciona tu carrera',
        placeHolderRole: 'Selecciona tu rol',
        placeHolderOtherMajor: 'UAEMex Nezahualcóyotl, Mecatrónica',
        button: 'Regístrate',
        alreadyHaveAccount: '¿Ya tienes una cuenta?',
    },
    modals: {
        otp: {
            title: 'Código de verificación',
            description: 'Ingresa el código de verificación dado por el administrador.',
        },
    },
    toast: {
        register: {
            success: 'Registrado con éxito',
        },
    },
    forgotPassword: {
        title: 'Restablece tu contraseña',
        description: 'Ingresa tu correo para recibir un enlace para restablecer tu contraseña.',
        button: 'Enviar enlace de restablecimiento',
        returnLogin: 'O bien, vuelve al apartado de',
    },
    common: {
        of: 'de',
        enter: 'Ingresar',
        password: 'Contraseña',
        newPassword: 'Nueva contraseña',
        currentPassword: 'Contraseña actual',
        confirmNewPassword: 'Confirmar nueva contraseña',
        email: 'Correo electrónico',
        placeHolderEmail: 'correo@ejemplo.com',
        placeHolderPassword: 'contraseña',
        termsAndConditions: 'Términos y condiciones',
        typeUser: 'Tipo de usuario',
        description: 'Descripción',
        accountNumber: 'Número de cuenta UAEMex',
        paternalSurname: 'Apellido paterno',
        maternalSurname: 'Apellido materno',
        name: 'Nombre(s)',
        origin: 'Origen',
        major: 'Carrera',
        role: 'Rol',
        other: 'Ingresa otra carrera',
        confirmPassword: 'Confirmar contraseña',
        settings: 'Ajustes',
        logout: 'Cerrar sesión',
        cancel: 'Cancelar',
        save: 'Guardar',
        saved: 'Guardado',
        send: 'Enviar',
        back: 'Atrás',
        warning: 'Advertencia',
    },
    verification: {
        unverified: 'No has verificado tu correo electrónico',
        resend: 'Reenviar correo de verificación',
        linkSent: 'Un nuevo enlace de verificación ha sido enviado a tu correo electrónico',
    },
    deleteAccount: {
        title: 'Eliminar cuenta',
        description: 'Esto eliminará permanentemente tu cuenta',
        advertence: 'Por favor, procede con cautela, esta acción es irreversible.',
        button: 'Eliminar cuenta',
        dialog: {
            title: '¿Estas seguro que quieres eliminar tu cuenta?',
            description:
                'Una vez borrada tu cuenta, toda la información asociada será permanentemente borrada. Por favor, ingresa tu contraseña para confirmar que quieres borrar permanentemente tu cuenta',
        },
    },
    settings: {
        title: 'Ajustes',
        description: 'Administra tu perfil y la configuración de tu cuenta',
        profile: {
            title: 'Perfil',
            subtitle: 'Información de tu perfil',
            description: 'Actualiza la información de tu perfil',
        },
        password: {
            title: 'Contraseña',
            subtitle: 'Actualiza tu contraseña',
            description: 'Asegurate de que tu contraseña sea fuerte y segura',
            button: 'Cambiar contraseña',
            success: 'Contraseña cambiada con éxito',
            error: 'Ha ocurrido un error al cambiar tu contraseña',
        },
        appearance: {
            title: 'Apariencia',
            subtitle: 'Personaliza tu apariencia',
            description: 'Escoje tu tema preferido',
            dark: 'Oscuro',
            light: 'Claro',
            system: 'Igual que el Sistema',
        },
    },
    footer: {
        useDisclaimer:
            'Esta página puede ser reproducida con fines no lucrativos, siempre y cuando se cite la fuente completa y su dirección electrónica, y no se mutile.',
        copyright: '© 2025 Todos los Derechos Reservados',
    },
    pagination: {
        page: 'Página',
        showing: 'Mostrando',
        items: 'elementos',
    },
};

export default texts;
